server_url: https://pixel-pandemonium-server.popyack.workers.dev
realtime_url: https://pixel-pandemonium-server.popyack.workers.dev
base_url: https://www.billmongan.com/PixelPandemonium_Client
default_expiration_hours: 8760
subcols: 5
subrows: 3
student_canvas_width: 500
student_canvas_height: 300
replay_cell_size: 24
