server_url: http://localhost:8000
realtime_url: http://localhost:8000
base_url: http://localhost:4000
default_expiration_hours: 72
subcols: 5
subrows: 3
student_canvas_width: 500
student_canvas_height: 300
replay_cell_size: 24
pictures:
  - id: tetris
    title: Demo (Tetris)
    script: files/drawingcanvas-tetris/Post-It_tetris_composite.js
  - id: cs4allpa2022
    title: CS4AllPA-2022
    script: files/drawingcanvas-cs4allpa2022/Post-It_CSforALLinPA_RWB_bk_v6x_composite.js
  - id: cs4philly2021
    title: CS4Philly-2021
    script: files/drawingcanvas-cs4philly2021/Post-It_CS4Philly_2021_v0_composite.js
  - id: cs4philly2022
    title: CS4Philly-2022
    script: files/drawingcanvas-cs4philly2022/Post-It_CS4Philly_2022_composite.js
  - id: eagles
    title: Eagles
    script: files/drawingcanvas-eagles/Post-It_Eagles_Logo_composite.js
  - id: eagles2
    title: Eagles2
    script: files/drawingcanvas-eagles2/Post-It_Eagles_Logo2_composite.js
  - id: ghopper
    title: GHopper
    script: files/drawingcanvas-ghopper/Post-It_CS4Philly_GHopper_composite.js
  - id: lovestatue
    title: LoveStatue
    script: files/drawingcanvas-lovestatue/Post-It_LOVE_Statue_composite.js
  - id: mikewazowski
    title: MikeWazowski
    script: files/drawingcanvas-mikewazowski/Post-It_MikeWazowski2_composite.js
  - id: phillyscifest
    title: PhillySciFest-2022
    script: files/drawingcanvas-phillyscifest/Post-It_Banner_PhillySciFest_v4_composite.js
  - id: pixar2022
    title: Pixar-2022
    script: files/drawingcanvas-pixar2022/Post-It_CS4Philly_Pixar_2022_composite.js
  - id: robotspringboard
    title: RobotSpringboard
    script: files/drawingcanvas-robotspringboard/Post-It_RobotSpringboard_2018_v2a_composite.js
  - id: robotspringboard2022
    title: RobotSpringboard-2022
    script: files/drawingcanvas-robotspringboard2022/Post-It_RobotSpringboard_2022_composite.js
  - id: rocky2022
    title: Rocky-2022
    script: files/drawingcanvas-rocky2022/Post-It_Rocky_ArtMuseum_2022_composite.js
  - id: yellowsubmarine
    title: YellowSubmarine
    script: files/drawingcanvas-yellowsubmarine/Post-It_YellowSubmarine_composite.js
  - id: yellowsubmarine2022
    title: YellowSubmarine-2022
    script: files/drawingcanvas-yellowsubmarine2022/Post-It_YellowSubmarine_2022_composite.js
